#!/bin/sh
[ ! -e ~/.ssh/authorized_keys ] && echo "No authorized key was provided." && exit 1
[ -w ~/.ssh/authorized_keys ] && chown root:root ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys

quit() {
    PID=$(cat /var/run/sshd/sshd.pid) && kill -SIGTERM "${PID}" && wait "${PID}"
}

if [ "$(basename $1)" == "sshd" ]; then
    trap quit SIGINT SIGTERM
    $@ &
    echo "$!" > /var/run/sshd/sshd.pid && wait "$!" && exit $?
else
    exec "$@"
fi
