#!/bin/sh
[ -f /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -A
[ -w ~/.ssh ] && chown root:root ~/.ssh && chmod 700 ~/.ssh/
[ -w ~/.ssh/authorized_keys ] && chown root:root ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
[ -d /var/run/sshd ] || mkdir -p /var/run/sshd
[ ! -e ~/.ssh/authorized_keys ] && echo "No authorized key was provided." && exit 1

quit() {
    PID=$(cat /var/run/sshd/sshd.pid) && kill -SIGTERM "${PID}" && wait "${PID}"
}

if [ "$(basename $1)" == "sshd" ]; then
    trap quit SIGINT SIGTERM
    $@ &
    echo "$!" > /var/run/sshd/sshd.pid && wait "$!" && exit $?
else
    exec "$@"
fi
