#!/bin/sh
quit() {
    stop-server
}

if [ "$(basename $1)" = 'start-server' ]; then
    if [ "$(id -u)" = '0' ]; then
        chown -R kafka:kafka .
        exec su-exec kafka:kafka "$0" "$@"
    fi

    trap quit SIGINT SIGTERM
    $@
else
    exec "$@"
fi
